// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prismaa.config.ts is the configuration file for Prisma, which defines how Prisma should connect to your database and where to find your schema and migrations. The code below sets up the configuration to use environment variables for the database connection string, and specifies the paths for the schema and migrations.
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
